"""Remote script bodies generated by the runner.

The training wrapper is byte-identical to the wrappers the milestone sweep
uploaded to Colab; the rescore body is the same code with the path root
substituted (``/content`` -> ``/work`` for the local container).
"""

from __future__ import annotations

from .types import Block, TrainJob, bundle_name


def train_wrapper(job: TrainJob, root: str) -> str:
    """The ``w_<name>.py`` body executed on the remote for ``job``."""
    argv = ", ".join(repr(arg) for arg in job.argv(root))
    return (
        "import sys\n"
        f"sys.path.insert(0, {root!r})\n"
        "for _m in ('train_ar', 'grammar_mask'):\n"
        "    sys.modules.pop(_m, None)\n"
        "import train_ar\n"
        f"train_ar.main([{argv}])\n"
    )


def rescore_jobs(block: Block, root: str) -> list[dict[str, str]]:
    """Remote paths for every RescoreJob of ``block`` (keys sorted on dump)."""
    source = bundle_name(block.source_bundle)
    jobs: list[dict[str, str]] = []
    for job in block.rescore:
        target = bundle_name(job.target_bundle)
        jobs.append({
            "run": job.source_run,
            "model": f"{root}/{job.source_run}_model.pt",
            "config": f"{root}/{job.source_run}_samples.json",
            "vocab": f"{root}/vocab_{source}.json",
            "meta": f"{root}/meta_{source}.json",
            "test": f"{root}/test_{target}.jsonl",
            "out": f"{root}/{job.source_run}__{target}.jsonl",
        })
    return jobs


def rescore_script(root: str) -> str:
    """Remote script that re-scores trained runs on their target bundles."""
    jobs_path = f"{root}/rescore_jobs.json"
    lines = [
        "import json",
        "import sys",
        "from pathlib import Path",
        "from types import SimpleNamespace",
        "",
        "import torch",
        "",
        f"sys.path.insert(0, {root!r})",
        "for _m in ('train_ar', 'grammar_mask'):",
        "    sys.modules.pop(_m, None)",
        "import train_ar",
        "",
        f"jobs = json.loads(Path({jobs_path!r}).read_text(encoding='utf-8'))",
        'device = torch.device("cuda" if torch.cuda.is_available() else "cpu")',
        "for job in jobs:",
        "    config = json.loads(",
        "        Path(job['config']).read_text(encoding='utf-8'))['config']",
        "    cfg = SimpleNamespace(**config)",
        "    vc = train_ar.Vocab(json.loads(",
        "        Path(job['vocab']).read_text(encoding='utf-8')))",
        "    meta = json.loads(Path(job['meta']).read_text(encoding='utf-8'))",
        "    gen_max_len = cfg.gen_max_len or 2 * meta['max_len']",
        "    model = train_ar.build_model(vc, meta, cfg, gen_max_len).to(device)",
        "    model.load_state_dict(torch.load(job['model'], map_location=device))",
        "    rows = train_ar.load_rows(job['test'])",
        "    scored = train_ar.score_rows(",
        "        model, rows, vc, device, cfg.struct_pos,",
        "        cfg.pointer or getattr(cfg, 'ref_legal_mask', False))",
        "    Path(job['out']).write_text(",
        "        ''.join(json.dumps(r) + '\\n' for r in scored), encoding='utf-8')",
        "    print(f\"RESCORED {job['run']} {job['test']} {len(scored)}\")",
        "print('RESCORE-DONE')",
    ]
    return "\n".join(lines) + "\n"
